export const notebooks = [
  {
    id: 1,
    title: 'Physics 101',
    description: 'Classical mechanics & thermodynamics',
    chapters: 12,
    pageCount: 234,
    lastStudied: 'Today',
    streak: 5,
    createdAt: '2026-01-15',
  },
  {
    id: 2,
    title: 'Calculus III',
    description: 'Multivariable calculus & vector analysis',
    chapters: 8,
    pageCount: 187,
    lastStudied: 'Yesterday',
    streak: 3,
    createdAt: '2026-02-20',
  },
  {
    id: 3,
    title: 'World History',
    description: 'Ancient civilizations to the modern era',
    chapters: 15,
    pageCount: 312,
    lastStudied: '3 days ago',
    streak: 0,
    createdAt: '2026-03-10',
  },
  {
    id: 4,
    title: 'Organic Chemistry',
    description: 'Functional groups, reactions & mechanisms',
    chapters: 10,
    pageCount: 198,
    lastStudied: '1 week ago',
    streak: 0,
    createdAt: '2026-04-05',
  },
];

export const topics = [
  { id: 1, notebookId: 1, title: 'Introduction to Motion', completed: true, order: 0, pageNumber: 3 },
  { id: 2, notebookId: 1, title: "Newton's Laws", completed: true, order: 1, pageNumber: 28 },
  { id: 3, notebookId: 1, title: 'Energy & Work', completed: false, order: 2, pageNumber: 52 },
  { id: 4, notebookId: 1, title: 'Momentum & Collisions', completed: false, order: 3, pageNumber: 78 },
  { id: 5, notebookId: 1, title: 'Rotational Dynamics', completed: false, order: 4, pageNumber: 104 },
  { id: 6, notebookId: 2, title: 'Vectors & Geometry', completed: true, order: 0, pageNumber: 1 },
  { id: 7, notebookId: 2, title: 'Partial Derivatives', completed: true, order: 1, pageNumber: 32 },
  { id: 8, notebookId: 2, title: 'Multiple Integrals', completed: false, order: 2, pageNumber: 67 },
  { id: 9, notebookId: 2, title: 'Vector Calculus', completed: false, order: 3, pageNumber: 98 },
  { id: 10, notebookId: 3, title: 'Ancient Mesopotamia', completed: true, order: 0, pageNumber: 1 },
  { id: 11, notebookId: 3, title: 'Classical Greece & Rome', completed: true, order: 1, pageNumber: 45 },
  { id: 12, notebookId: 3, title: 'Medieval Era', completed: false, order: 2, pageNumber: 112 },
  { id: 13, notebookId: 3, title: 'Renaissance & Enlightenment', completed: false, order: 3, pageNumber: 178 },
  { id: 14, notebookId: 4, title: 'Alkanes & Cycloalkanes', completed: true, order: 0, pageNumber: 1 },
  { id: 15, notebookId: 4, title: 'Stereochemistry', completed: true, order: 1, pageNumber: 38 },
  { id: 16, notebookId: 4, title: 'Alkyl Halides & SN Reactions', completed: false, order: 2, pageNumber: 72 },
  { id: 17, notebookId: 4, title: 'Alkenes & Alkynes', completed: false, order: 3, pageNumber: 109 },
];

export const messages = [
  {
    id: 1,
    notebookId: 1,
    role: 'ai',
    text: "Hello! I'm your AI tutor. Which notebook shall we study today?",
    timestamp: '2026-07-08T10:00:00Z',
  },
  {
    id: 2,
    notebookId: 1,
    role: 'user',
    text: "Can you explain Newton's Third Law?",
    timestamp: '2026-07-08T10:05:00Z',
  },
  {
    id: 3,
    notebookId: 1,
    role: 'ai',
    text: "Of course. Newton's Third Law states that for every action, there is an equal and opposite reaction. When you push against a wall, the wall pushes back with the same force in the opposite direction. The forces come in pairs — they act on different objects, which is why motion can still occur despite equal forces.",
    timestamp: '2026-07-08T10:05:30Z',
  },
  {
    id: 4,
    notebookId: 1,
    role: 'user',
    text: 'Can you give me a real-world example?',
    timestamp: '2026-07-08T10:07:00Z',
  },
  {
    id: 5,
    notebookId: 1,
    role: 'ai',
    text: "A rocket launching is a perfect example. The rocket engine expels exhaust gases downward (action), and the gases push the rocket upward with an equal force (reaction). This is why rockets can accelerate in the vacuum of space — they don't need to push against the ground or air.",
    timestamp: '2026-07-08T10:07:15Z',
  },
  {
    id: 6,
    notebookId: 2,
    role: 'ai',
    text: "Welcome to Calculus III! I'm here to help with multivariable calculus, vector fields, and surface integrals. What would you like to explore?",
    timestamp: '2026-07-07T14:00:00Z',
  },
  {
    id: 7,
    notebookId: 3,
    role: 'ai',
    text: 'Ready to journey through history? From ancient Mesopotamia to the Enlightenment, I can help you understand the connections between events, cultures, and ideas.',
    timestamp: '2026-07-05T09:30:00Z',
  },
  {
    id: 8,
    notebookId: 4,
    role: 'ai',
    text: 'Organic Chemistry awaits! We can explore functional groups, reaction mechanisms, and spectroscopy together. Where would you like to begin?',
    timestamp: '2026-06-30T16:00:00Z',
  },
];

export const marginalia = [
  { id: 1, notebookId: 1, topicId: 2, text: 'Review w/ prof Tue', rotation: -2, x: 10, y: 40, createdAt: '2026-07-07' },
  { id: 2, notebookId: 1, topicId: 1, text: 'Check example 3.7', rotation: 3, x: 15, y: 120, createdAt: '2026-07-06' },
  { id: 3, notebookId: 1, topicId: 3, text: 'Ask about conservation', rotation: -1.5, x: 12, y: 200, createdAt: '2026-07-05' },
];
